# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"  # this enabled searching only in /.github/workflows directory
      - "/.github/actions/bootstrap"
      - "/.github/actions/clamav"
      - "/dev-version-update"
      - "/discover-changed-files"
      - "/discover-changed-subfolders"
      - "/verify-branch-name"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
