---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# Bandit Scanner Action
#
# This composite action executes Signing binaries or images,
# using Cosign tool:
# https://docs.sigstore.dev/quickstart/quickstart-cosign/
# https://github.com/sigstore/cosign

name: 'Sign Image or Binary with Cosign'
description: 'Signs container images or binaries using Cosign.'

inputs:
  target:
    description: 'What to sign: "image" or "binary"'
    required: true
  artifact:
    description: 'Full image reference (e.g., ghcr.io/org/app:tag) or binary path (e.g., ./bin/app)'
    required: true
  environment:
    description: 'Environment to sign for (prod or non-prod)'
    required: false
    default: 'non-prod'
  gh_token:
    description: 'GitHub token used for registry auth'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: 'v2.5.2'

    - name: Login to GitHub Container Registry
      if: ${{ inputs.target == 'image' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        echo "$GH_TOKEN" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Sign image or binary with Cosign
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
        ARTIFACT: ${{ inputs.artifact }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        set -euo pipefail

        echo "🔏 Signing $TARGET: $ARTIFACT"

        # Determine whether to upload to transparency log
        if [ "$ENVIRONMENT" = "prod" ]; then
          TLOG_FLAG=""
        else
          TLOG_FLAG="--tlog-upload=false"
        fi

        # Perform signing
        if [ "$TARGET" = "image" ]; then
          cosign sign \
            --yes \
            --bundle cosign.bundle.json \
            --output-signature cosign.sig \
            --output-certificate cosign.cert \
            $TLOG_FLAG \
            "$ARTIFACT"
        elif [ "$TARGET" = "binary" ]; then
          if [ ! -f "$ARTIFACT" ]; then
            echo "❌ Binary not found at path: $ARTIFACT"
            exit 1
          fi
          cosign sign-blob \
            --yes \
            --bundle cosign.bundle.json \
            --output-signature cosign.sig \
            --output-certificate cosign.cert \
            $TLOG_FLAG \
            "$ARTIFACT"
        else
          echo "❌ Invalid target: $TARGET (must be image or binary)"
          exit 1
        fi

        echo "✅ Signing complete."
        ls -lh cosign.*

    - name: Verify signature
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
        ARTIFACT: ${{ inputs.artifact }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        set -euo pipefail

        echo "🧾 Verifying $TARGET: $ARTIFACT"

        CERT_IDENTITY="https://github.com/${GITHUB_REPOSITORY}/.*/github-actions"
        OIDC_ISSUER="https://token.actions.githubusercontent.com"

        if [ "$TARGET" = "image" ]; then
          cosign verify \
            --bundle cosign.bundle.json \
            --certificate-identity-regexp "$CERT_IDENTITY" \
            --certificate-oidc-issuer "$OIDC_ISSUER" \
            "$ARTIFACT"
        elif [ "$TARGET" = "binary" ]; then
          cosign verify-blob \
            --bundle cosign.bundle.json \
            --certificate-identity-regexp "$CERT_IDENTITY" \
            --certificate-oidc-issuer "$OIDC_ISSUER" \
            "$ARTIFACT"
        else
          echo "❌ Invalid target for verification: $TARGET"
          exit 1
        fi

        echo "🟢 Verification finished successfully."
