---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: 'Verify Branch Name'
description: "Verify branch name"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        persist-credentials: false
    - name: Verify branch name
      env:
        HEAD_REF: ${{ github.head_ref }}
      shell: bash
      run: |
        if [[ "${HEAD_REF}" =~ ^(main|release-.*)$ ]]; then
          echo "Not allowed branch name!"
          exit 1
        fi
