---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: 'Verify Branch Name'
runs:
  using: "composite"
  env:
    HEAD_REF: ${{ github.head_ref }}
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Verify branch name
      shell: bash
      run: |
        if [[ "${HEAD_REF}" =~ ^(main|release-.*)$ ]]; then
          echo "Not allowed branch name!"
          exit 1
        fi
