---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "Check PR Title"
description: "Checks if the pull request title follows Conventional Commits format."
inputs:
  pr_title:
    description: "The title of the pull request."
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Checking PR title: ${{ inputs.pr_title }}"
        convcommit="^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(\([a-z0-9_-]+\))?:\ [A-Z].+"
        if [[ ! ${{ inputs.pr_title }} =~ $convcommit ]]; then
          echo "Error: Pull request title does not follow Conventional Commits format."
          echo "Expected format: <type>(<scope>): <description>"
          echo "Example: feat(parser): add ability to parse arrays"
          exit 1
        fi
