---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: 'Update Pull Requests'
description: 'Update all pull requests to the head of their respective base branches'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Authenticate with GitHub CLI
      env:
        github_token: ${{ inputs.github_token }}
      shell: bash
      run: echo "${github_token}" | gh auth login --with-token

    - name: Update pull requests
      shell: bash
      run: |
        PRs=$(gh pr list --json number --jq '.[].number')

        for PR in $PRs; do
          echo "Updating PR #$PR"
          # Attempt to merge the base branch into the pull request branch
          gh pr checkout $PR
          BASE_BRANCH=$(gh pr view $PR --json baseRefName --jq '.baseRefName')
          git merge origin/$BASE_BRANCH || echo "Failed to merge base branch into PR #$PR"
          git push || echo "Failed to push updates for PR #$PR"
        done
