---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: 'Publish Documentation'

on:  # yamllint disable-line rule:truthy rule:line-length
  workflow_call:
    inputs:
      docs_directory:
        description: >-
          Documentation directory where the job will run, defaults to '.'
        required: false
        default: "."
        type: string
      output_directory:
        description: >-
          Directory where the documentation HTML build is located,
          defaults to 'out/html'
        required: false
        default: "out/html"
        type: string
      branch_pattern:
        description: >-
          Regex pattern to match against when selecting branches to build for
          version selector, defaults to '^(main|release-.*)$'
        required: false
        default: '^(main|release-.*)$'
        type: string
      simple_mode:
        description: >-
          When true, override configuration for simple documentation sites
        required: false
        default: true
        type: boolean
      orch_ci_repo_ref:
        description: >-
          The ref of the orch-ci repo, including bootstrap action and scripts,
          defaults to 'main'
        required: false
        default: "main"
        type: string
      endpoint:
        description: >-
          Endpoint URL where documentation will be deployed to,
          defaults to 's3://intel-openedgeplatform-documentation'
        required: false
        default: "s3://intel-openedgeplatform-documentation"
        type: string
      distribution_id:
        description: >-
          Distribution ID of documentation hosting service,
          defaults to 'E1QN7TZJG8M0VL'
        required: false
        default: "E1QN7TZJG8M0VL"
        type: string

permissions:
  contents: write
jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    env:
      DOCS_DIR: ${{ inputs.docs_directory }}
      OUT_DIR: ${{ inputs.output_directory }}
      REF_NAME: ${{ github.ref_name }}
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout action repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: open-edge-platform/orch-ci
          path: ci
          ref: ${{ inputs.orch_ci_repo_ref }}
          token: ${{ secrets.SYS_ORCH_GITHUB }}

      - name: Bootstrap CI environment
        uses: ./ci/.github/actions/bootstrap
        with:
          gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
          bootstrap_tools: "aws"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722  # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          # Fetch all history, otherwise sporadic issue with missing tags
          fetch-depth: 0
          # Fetch tags
          fetch-tags: true
          # Checkout the branch that triggered the workflow
          # to avoid detached HEAD
          ref: ${{ github.head_ref }}

      # Use orch-docs as a template
      - name: Checkout template
        if: ${{ inputs.simple_mode }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: open-edge-platform/orch-docs
          ref: main
          path: _template
          persist-credentials: false
          sparse-checkout: |
            docconf
            Makefile
            requirements.txt
            dict.txt
            docs/conf.py
            docs/substitutions.txt
          sparse-checkout-cone-mode: false

      - name: Copy template
        if: ${{ inputs.simple_mode }}
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}/${DOCS_DIR}"
          # Override any existing files with template
          cp -rf "${GITHUB_WORKSPACE}"/_template/* .

      - name: Collect branches
        env:
          PATTERN: ${{ inputs.branch_pattern }}
        shell: bash
        run: |
          # Remove ci directory
          rm -rf "${GITHUB_WORKSPACE}/ci"
          # Get list of all branches on remote to build
          mapfile -t branches < <(git ls-remote --heads | cut -f3- -d/)
          for index in "${!branches[@]}"; do
            if echo "${branches[$index]}" | grep -qEv "${PATTERN}"; then
              unset -v 'branches[$index]'
            fi
          done
          if [[ -z "${branches[*]}" ]]; then
            echo "ERROR: No branches matched 'branch_pattern': ${PATTERN}"
            exit 1
          fi
          # Convert the array to a string with comma delimeters
          branches=$(IFS=','; echo "${branches[*]}")
          echo "DOCS_BRANCHES=${branches}" >> "$GITHUB_ENV"

      - name: Get Subdirectory
        shell: bash
        run: |
          # Replace the strings in ["example"] with the assigned string
          # Create associative array
          declare -A REPLACE
          REPLACE=(
              ["orch-docs"]="edge-manage-docs"
          )
          # Convert '.' to '/'
          rshort="${REPO//./\/}"
          # Retrieve word after last '/'
          rshort="${rshort##*/}"
          # Replace matches if found
          if [[ -v REPLACE[$rshort] ]]; then
            rshort="${REPLACE[$rshort]}"
          fi
          # Get last name in path
          path="$(basename "${DOCS_DIR}")"
          # Remove any '.' characters
          path="${path//./}"
          # If path exists, append it
          if [[ -n "${path}" ]]; then
            subdir="${rshort}/${path}"
          else
            subdir="${rshort}"
          fi
          echo "SUBDIR=${subdir}" >> "$GITHUB_ENV"

      - name: Install Spark theme
        env:
          ENDPOINT: ${{ inputs.endpoint }}
          DOCS_BRANCHES: ${{ env.DOCS_BRANCHES }}
        shell: bash
        run: |
          # Restore array
          IFS=',' read -ra branches <<< "${DOCS_BRANCHES}"
          # Download Spark Sphinx theme
          tmpdir="$(mktemp -d)"
          aws s3 cp "${ENDPOINT}/theme/current" "${tmpdir}"
          theme_wheel="$(cat "${tmpdir}/current")"
          aws s3 cp "${ENDPOINT}/theme/${theme_wheel}" "${tmpdir}"
          # Checkout the first branch to build
          cd "${GITHUB_WORKSPACE}"
          git checkout "${branches[0]}"
          cd "${DOCS_DIR}"
          # Instantiate Python Virtual Environment
          make check
          venv="$(find . -path '*/bin/activate' -name activate)"
          # shellcheck source=/dev/null
          source "${venv}"
          # Install Spark Sphinx theme
          pip3 install --no-input "${tmpdir}/${theme_wheel}"
          deactivate

      - name: Build Documentation
        env:
          SIMPLE_MODE: ${{ inputs.simple_mode }}
          DOCS_BRANCHES: ${{ env.DOCS_BRANCHES }}
        shell: bash
        run: |
          # Restore array
          IFS=',' read -ra branches <<< "${DOCS_BRANCHES}"
          for branch in "${branches[@]}"; do
            cd "${GITHUB_WORKSPACE}"
            git reset --hard
            git checkout "${branch}"
            cd "${DOCS_DIR}"
            if [ "${SIMPLE_MODE}" == 'true' ]; then
              # Override any existing files with template
              cp -rf "${GITHUB_WORKSPACE}"/_template/* .
              if [ -f "docs/dictionary_append.txt" ]; then
                cat "docs/dictionary_append.txt" >> "dict.txt"
              fi
            fi
            echo "Building branch: ${branch}"
            make build
            if [[ ! -d "${OUT_DIR}" ]]; then
              echo "ERROR: Build directory does not exist for branch:"
              echo "${branch}"
              exit 1
            fi
            mkdir -p "${GITHUB_WORKSPACE}/_UPLOAD/${branch}"
            mv "${OUT_DIR}"/* "${GITHUB_WORKSPACE}/_UPLOAD/${branch}"
            make clean || :
            rm -rf "${OUT_DIR}"
          done

      - name: Trim release prefix
        env:
          DOCS_BRANCHES: ${{ env.DOCS_BRANCHES }}
        shell: bash
        run: |
          # Restore array
          IFS=',' read -ra branches <<< "${DOCS_BRANCHES}"
          for branch in "${branches[@]}"; do
            # Find branches that match patterns:
            # release-#.# or release-#.#.#
            if echo "${branch}" | grep -qE '^release-\d(\.\d){1,2}$'; then
              version="${branch#*-}"
              mv "${GITHUB_WORKSPACE}/_UPLOAD/${branch}" \
                "${GITHUB_WORKSPACE}/_UPLOAD/${version}"
            fi
          done

      - name: Publish documentation
        env:
          ENDPOINT: ${{ inputs.endpoint }}
          DISTID: ${{ inputs.distribution_id }}
          SUBDIR: ${{ env.SUBDIR }}
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}/_UPLOAD"
          aws s3 rm "${ENDPOINT}/${SUBDIR}" --include "*" --recursive
          aws s3 cp --include "*" --recursive . "${ENDPOINT}/${SUBDIR}"
          aws cloudfront create-invalidation \
            --distribution-id "${DISTID}" --paths "/${SUBDIR}/*"
          echo "Publishing documentation complete."
          # Remove ci directory
          rm -rf "${GITHUB_WORKSPACE}/ci"

      - name: Create comment with link in PR
        env:
          SUBDIR: ${{ env.SUBDIR }}
          DOCS_BRANCHES: ${{ env.DOCS_BRANCHES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR: ${{ github.event.pull_request.number }}
        shell: bash
        run: |
          # Restore array
          IFS=',' read -ra branches <<< "${DOCS_BRANCHES}"
          # Use GitHub API to create a comment on the PR
          COMMENT="Documentation published at: "
          COMMENT+="https://docs.openedgeplatform.intel.com/"
          COMMENT+="${SUBDIR}/${branches[0]}/"
          COMMENT_URL="https://api.github.com/repos/"
          COMMENT_URL+="${REPO}/issues/${GITHUB_PR}/comments"
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            -X POST "${COMMENT_URL}" -d "{\"body\":\"$COMMENT\"}" || :

      # Checkout orch-ci again so the
      # 'Post Bootstrap CI Environment' step does not fail
      - name: Checkout action repository
        if: always()
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: open-edge-platform/orch-ci
          path: ci
          ref: ${{ inputs.orch_ci_repo_ref }}
          token: ${{ secrets.SYS_ORCH_GITHUB }}
